/*
 * Copyright (C) 2018 Rurikk
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package main.java.gui;

import main.java.sgh.Hospital;
import main.java.utiles.Rut;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.GridBagLayout;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import javax.swing.JLabel;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;

/**
 *
 * @author Rurikk
 */
public class HabitacionesAgregarModificarFrame extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form HabitacionesAgregarModificarFrame
     */
	private Hospital hospi;
    public HabitacionesAgregarModificarFrame(Hospital hospi) {
        initComponents();
        this.hospi=hospi;
    }
    public HabitacionesAgregarModificarFrame()
    {
    	setTitle("Datos");
    	initComponents();
    	this.hospi=null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoGrupo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Times New Roman", Font.PLAIN, 20));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 15));
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldEspecialidad = new javax.swing.JTextField();
        jRadioButtonConsulta = new javax.swing.JRadioButton();
        jRadioButtonHospitalizados = new javax.swing.JRadioButton();
        jTextFieldCapacidad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Agregar");

        jLabel2.setText("Datos");

        jTextFieldID.setText("ID");

        jTextFieldEspecialidad.setText("Especialidad");

        tipoGrupo.add(jRadioButtonConsulta);
        jRadioButtonConsulta.setText("Consulta");

        tipoGrupo.add(jRadioButtonHospitalizados);
        jRadioButtonHospitalizados.setText("Hospitalizados");

        jTextFieldCapacidad.setText("Capacidad");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("id");

        jLabel4.setText("especialidad");
        
        txtRut = new JTextField();
        txtRut.setText("Rut");
        txtRut.setColumns(10);
        
        JLabel lblRutEncargado = new JLabel("Rut Encargado");
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(160)
        					.addComponent(jLabel1))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(24)
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel3)
        						.addComponent(jLabel2)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jTextFieldID, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jButton1)
        								.addComponent(jRadioButtonConsulta)
        								.addComponent(jTextFieldCapacidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        							.addGap(3)
        							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        								.addGroup(groupLayout.createSequentialGroup()
        									.addGap(68)
        									.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        										.addComponent(jTextFieldEspecialidad, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
        										.addComponent(jRadioButtonHospitalizados, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)
        										.addComponent(jLabel4)))
        								.addGroup(groupLayout.createSequentialGroup()
        									.addGap(88)
        									.addComponent(jButton2))))
        						.addGroup(groupLayout.createSequentialGroup()
        							.addComponent(lblRutEncargado)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(txtRut, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        					.addGap(20)))
        			.addGap(85))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(13)
        					.addComponent(jLabel1))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(30)
        					.addComponent(jLabel2)))
        			.addGap(10)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(jLabel4))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextFieldID, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTextFieldEspecialidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jRadioButtonConsulta)
        				.addComponent(jRadioButtonHospitalizados))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jTextFieldCapacidad, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(22)
        					.addComponent(txtRut, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(lblRutEncargado)))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jButton2))
        			.addGap(32))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        HabitacionesListadoFrame personas = new HabitacionesListadoFrame(hospi);
        //muestra la ventana de carga
        personas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Rut run=null;
        try {
            
            MenuPrincipalFrame menu=new MenuPrincipalFrame(hospi);
    	MensajeCorrecto msj=new MensajeCorrecto();
    	MensajeFallido msjFail=new MensajeFallido();
    	if(jRadioButtonConsulta.isSelected() && !jRadioButtonHospitalizados.isSelected())                                         
    	{
    		run=new Rut(txtRut.getText());
            try {
                if(hospi.agregarHabitacionConsulta(jTextFieldID.getText(), jTextFieldEspecialidad.getText(),run))
                {
                    msj.setVisible(true);
                    menu.setVisible(true);
                    this.dispose();
                }
                else
                {
                    msjFail.setVisible(true);
                    this.dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(HabitacionesAgregarModificarFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    	}
    	if(!jRadioButtonConsulta.isSelected() && jRadioButtonHospitalizados.isSelected())
    	{
    		run=new Rut(txtRut.getText());
            try {
                if(hospi.agregarHabitacionHospitalizados(jTextFieldID.getText(), jTextFieldEspecialidad.getText(), run, Integer.parseInt((jTextFieldCapacidad.getText()))))
                {
                    msj.setVisible(true);
                    menu.setVisible(true);
                    this.dispose();
                }
                else
                {
                    msjFail.setVisible(true);
                    this.dispose();
                }
            } catch (SQLException ex) {
                Logger.getLogger(HabitacionesAgregarModificarFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    	}
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HabitacionesAgregarModificarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HabitacionesAgregarModificarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HabitacionesAgregarModificarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HabitacionesAgregarModificarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HabitacionesAgregarModificarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButtonConsulta;
    private javax.swing.JRadioButton jRadioButtonHospitalizados;
    private javax.swing.JTextField jTextFieldCapacidad;
    private javax.swing.JTextField jTextFieldEspecialidad;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.ButtonGroup tipoGrupo;
    private JTextField txtRut;
}
