/*
 * Copyright (C) 2018 Rurikk
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package main.java.gui;

import main.java.sgh.Consulta;
import main.java.sgh.Hospital;
import main.java.sgh.Hospitalizados;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import javax.swing.table.DefaultTableModel;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
//import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Rurikk
 */
public class HabitacionesListadoFrame extends javax.swing.JFrame {

    /**
     * Creates new form HabitacionesFrame
     */
	private Hospital hospi;
    public HabitacionesListadoFrame(Hospital hospi) {
    	setTitle("Habitaciones");
        initComponents();
        this.hospi=hospi;
    }

    /*public HabitacionesListadoFrame() {
    	GroupLayout groupLayout = new GroupLayout(getContentPane());
    	groupLayout.setHorizontalGroup(
    		groupLayout.createParallelGroup(Alignment.LEADING)
    			.addGap(0, 584, Short.MAX_VALUE)
    	);
    	groupLayout.setVerticalGroup(
    		groupLayout.createParallelGroup(Alignment.LEADING)
    			.addGap(0, 321, Short.MAX_VALUE)
    	);
    	getContentPane().setLayout(groupLayout);
		// TODO Auto-generated constructor stub
	}*/

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoHabitacion = new javax.swing.ButtonGroup();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelTitulo.setFont(new Font("Times New Roman", Font.PLAIN, 25));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHabitaciones = new javax.swing.JTable();
        jButtonAgregar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonMostrar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setText("Habitaciones");

        jTableHabitaciones.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		{null, null, null, null, null, null, null},
        		
        	},
        	new String[] {
        		"ID", "Disponible", "Especialidad", "Encargado Medico o Enfermero", "Camas Ocupadas", "Camas Total", "Tipo"
        	}
        ));
        
        
        jScrollPane1.setViewportView(jTableHabitaciones);

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Volver");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        
        btnMostrarDatos = new JButton("Mostrar Datos");
        btnMostrarDatos.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		for(int i=0;i<hospi.cantidadHabitacionesConsulta()+hospi.cantidadHabitacionesHospitalizados();i++)
                {
                	jTableHabitaciones.setValueAt(hospi.mostrarHabitacionPorPosicion(i).getId(),i,0);
                	jTableHabitaciones.setValueAt(hospi.mostrarHabitacionPorPosicion(i).getDisponibilidad(),i , 1);
                	if(hospi.mostrarHabitacionPorPosicion(i) instanceof Hospitalizados)
                	{
                		jTableHabitaciones.setValueAt(((Hospitalizados)(hospi.mostrarHabitacionPorPosicion(i))).getRutEnfermero(),i, 3);
                		jTableHabitaciones.setValueAt(((Hospitalizados)(hospi.mostrarHabitacionPorPosicion(i))).camasDisponibles(),i, 4);
                	    jTableHabitaciones.setValueAt(((Hospitalizados)(hospi.mostrarHabitacionPorPosicion(i))).getCapacidad(),i, 5);
                	    jTableHabitaciones.setValueAt("Hospitalizados",i, 6);
                	}
                	if(hospi.mostrarHabitacionPorPosicion(i) instanceof Consulta)
                	{
                		jTableHabitaciones.setValueAt(((Consulta)(hospi.mostrarHabitacionPorPosicion(i))).getRutMedico(), i, 3);
                		jTableHabitaciones.setValueAt(1,i, 4);
                		jTableHabitaciones.setValueAt(1,i, 5);
                		jTableHabitaciones.setValueAt("Consulta",i, 6);
                	}
                	jTableHabitaciones.setValueAt(hospi.mostrarHabitacionPorPosicion(i).getEspecialidad(),i, 2);
                }
        	}
        });
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addContainerGap(24, Short.MAX_VALUE)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addComponent(jButtonAgregar)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(26)
        							.addComponent(jButtonModificar)
        							.addGap(18)
        							.addComponent(jButtonEliminar, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(jButtonMostrar)
        							.addGap(12)
        							.addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 86, GroupLayout.PREFERRED_SIZE))
        						.addGroup(groupLayout.createSequentialGroup()
        							.addComponent(jLabelTitulo)
        							.addPreferredGap(ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
        							.addComponent(btnMostrarDatos)
        							.addGap(14))))
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 516, GroupLayout.PREFERRED_SIZE))
        			.addGap(84))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(26)
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addComponent(jLabelTitulo)
        					.addGap(18))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addComponent(btnMostrarDatos)
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 156, GroupLayout.PREFERRED_SIZE)
        			.addGap(30)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButtonAgregar)
        				.addComponent(jButtonModificar)
        				.addComponent(jButtonEliminar)
        				.addComponent(jButtonMostrar)
        				.addComponent(jButton5))
        			.addGap(43))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        HabitacionesAgregarModificarFrame personas = new HabitacionesAgregarModificarFrame(hospi);
        //muestra la ventana de carga
        personas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        HabitacionesEliminarFrame personas = new HabitacionesEliminarFrame(hospi);
        //muestra la ventana de carga
        personas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            
        MenuPrincipalFrame personas = new MenuPrincipalFrame(hospi);
        //muestra la ventana de carga
        personas.setVisible(true);
        } catch (Exception e) {
        }
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    	
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        HabitacionesDetallesCamasFrame personas = new HabitacionesDetallesCamasFrame(hospi);
        //muestra la ventana de carga
        personas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	Hospital hospi=null;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HabitacionesListadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HabitacionesListadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HabitacionesListadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HabitacionesListadoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
                new HabitacionesListadoFrame(hospi).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHabitaciones;
    private javax.swing.ButtonGroup tipoHabitacion;
    private JButton btnMostrarDatos;
}
